# Generated by Django 3.1 on 2020-11-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_manager', '0003_auto_20201125_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
