# Generated by Django 3.1 on 2020-11-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_manager', '0005_auto_20201125_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='session_token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Token',
        ),
    ]
