# Generated by Django 3.1 on 2020-11-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_manager', '0006_auto_20201125_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='session_token',
        ),
        migrations.AddField(
            model_name='player',
            name='session_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
