# Generated by Django 3.1 on 2020-11-26 13:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_manager', '0007_auto_20201125_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 26, 13, 47, 45, 9260, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
