# Generated by Django 3.1 on 2020-11-26 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_manager', '0008_player_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='active_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='hotel_manager.room'),
        ),
        migrations.CreateModel(
            name='RoomPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_manager.player')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_manager.room')),
            ],
        ),
    ]
