# Generated by Django 3.1 on 2020-12-02 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('werewolf', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='Setting',
        ),
    ]
