# Generated by Django 3.1 on 2020-12-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werewolf', '0002_auto_20201202_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='value',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
