# Generated by Django 3.1 on 2020-12-02 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_manager', '0011_auto_20201129_1410'),
        ('werewolf', '0003_auto_20201202_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='value',
            new_name='default_value',
        ),
        migrations.CreateModel(
            name='WerewolfGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_manager.room')),
            ],
        ),
        migrations.CreateModel(
            name='GameSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=25)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='werewolf.werewolfgame')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='werewolf.setting')),
            ],
        ),
    ]
